# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# http://jekyll.github.io/jekyll-seo-tag/usage/
title: Josef Šustáček
email: js&commat;josefsustacek.cz
description: >-
  Josef Šustáček -- Java Developer and Software Engineer with over 15 years of experience, ex-Liferay Global Services consultant.
  Java, Amazon Web Services (AWS), CI/CD, Tomcat, nginx, Gradle, git, best practices, code reviews.

baseurl: ""                           # the subpath of your site, e.g. /blog
url: "https://www.josefsustacek.cz"   # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sustacek
github_username:  sustacek
linkedin_username: josefsustacek

# BEGIN Custom variables
phone: +420 777 693 353
# END Custom variables

# Build settings
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-paginate

# Config available for the "minima" theme 
header_pages:
  - index.md
  - _pages/about.md
  - _pages/blog.md
  - _pages/personal-finance.md
  - _pages/woodworking.md
  - _pages/contact.md

show_excerpts: true   # in list of posts on "home" layout

# TODO make the pagination work; test on GitHub
# paginate: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - files/resume/*.pages

include:
  - _pages
