# Local init: 
#     docker run -v $(pwd):/site bretfisher/jekyll new .

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'

    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./
    #       target: /site